# Practico Mentoria - Analisis Exploratorio y Curación de Datos

---

### Importaciones

In [8]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

from sklearn import preprocessing

import warnings
warnings.filterwarnings('ignore')

In [9]:
# Set seed for reproducibility
np.random.seed(0)

In [10]:
player_df = pd.read_csv('./Datasets/football_player.csv')
team_df = pd.read_csv('./Datasets/football_team.csv')
match_df = pd.read_csv('./Datasets/football_match.csv')

In [11]:
print("Shape 'player_df' = {}".format(player_df.shape))
print("Shape 'team_df'   = {}".format(team_df.shape))
print("Shape 'match_df'  = {}".format(match_df.shape))

Shape 'player_df' = (11060, 40)
Shape 'team_df'   = (288, 22)
Shape 'match_df'  = (25979, 12)

---

# 1. Importacion de los datos

Calculemos el rango de fechas de los partidos

In [12]:
match_df['date'].max() - match_df['date'].min()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Indiquemos que la columna `date` es una fechas como indica la [documentación](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#datetime-handling)

In [19]:
match_df['date'].max()

'2016-05-25 00:00:00'

In [21]:
match_df['date'].min()

'2008-07-18 00:00:00'

In [23]:
match_df.dtypes

country name            object
league name             object
season                  object
stage                    int64
date                    object
home team long name     object
home short long name    object
away team long name     object
away short long name    object
home team goal           int64
away team goal           int64
total goal               int64
dtype: object

In [26]:
match_df['Fecha'] =  pd.to_datetime(match_df['date'])

In [27]:
match_df.dtypes

country name                    object
league name                     object
season                          object
stage                            int64
date                            object
home team long name             object
home short long name            object
away team long name             object
away short long name            object
home team goal                   int64
away team goal                   int64
total goal                       int64
Fecha                   datetime64[ns]
dtype: object

In [32]:
match_df['Fecha']

0       2008-08-17
1       2008-08-16
2       2008-08-16
3       2008-08-17
4       2008-08-16
5       2008-09-24
6       2008-08-16
7       2008-08-16
8       2008-08-16
9       2008-11-01
10      2008-10-31
11      2008-11-02
12      2008-11-01
13      2008-11-01
14      2008-11-01
15      2008-11-01
16      2008-11-01
17      2008-11-02
18      2008-11-08
19      2008-11-08
20      2008-11-09
21      2008-11-07
22      2008-11-08
23      2008-11-08
24      2008-11-08
25      2008-11-08
26      2008-11-09
27      2008-11-16
28      2008-11-15
29      2008-11-15
           ...
25949   2015-08-08
25950   2015-08-08
25951   2015-08-09
25952   2015-08-09
25953   2015-08-09
25954   2015-08-12
25955   2015-08-12
25956   2015-08-12
25957   2015-08-13
25958   2015-08-13
25959   2015-08-22
25960   2015-08-23
25961   2015-08-23
25962   2015-08-23
25963   2015-08-22
25964   2015-08-29
25965   2015-08-29
25966   2015-08-30
25967   2015-08-30
25968   2015-08-30
25969   2015-09-12
25970   2015-09-12
25971   2015-09-13
25972   2015-09-13
25973   2015-09-13
25974   2015-09-22
25975   2015-09-23
25976   2015-09-23
25977   2015-09-22
25978   2015-09-23
Name: Fecha, Length: 25979, dtype: datetime64[ns]

In [33]:
match_df['Fecha'].max()

Timestamp('2016-05-25 00:00:00')

In [34]:
match_df['Fecha'].min()

Timestamp('2008-07-18 00:00:00')

In [35]:
match_df['Fecha'].max() - match_df['Fecha'].min()

Timedelta('2868 days 00:00:00')

Existen 2868 días de diferencia entre la fecha minima y la maxima

Por otro lado podríamos leer directamente el dataframe paresando en la lectura el campo DATE a fecha

In [40]:
match_df_parseDate = pd.read_csv('./Datasets/football_match.csv', parse_dates=["date"])
match_df_parseDate.dtypes

country name                    object
league name                     object
season                          object
stage                            int64
date                    datetime64[ns]
home team long name             object
home short long name            object
away team long name             object
away short long name            object
home team goal                   int64
away team goal                   int64
total goal                       int64
dtype: object

In [41]:
match_df_parseDate['date'].max() - match_df_parseDate['date'].min()

Timedelta('2868 days 00:00:00')

Es otra forma de hacer el calculo

# 2. Etiquetas de variables/columnas: no usar caracteres especiales

Chequar que no haya caracteres fuera de `a-Z`, `0-9` y `_` en los nombres de columnas de los Dataframes:
* `player_df`
* `team_df`
* `match_df`

In [36]:
player_df.describe()

,height_m,weight_kg,overall_rating,potential,crossing,finishing,heading accuracy,short passing,volleys,dribbling,...,vision,penalties,marking,standing tackle,sliding tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
count,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,10582.000000,11060.000000,...,10582.000000,11060.000000,11060.000000,11060.000000,10582.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000
mean,1.817847,76.375393,66.821222,72.090216,52.853855,47.862155,56.100191,60.367143,47.110973,56.892354,...,55.866959,53.683902,46.231480,49.440716,47.124626,14.911413,16.676659,23.015325,16.750476,17.055242
std,0.063278,6.799564,6.237719,5.800313,16.169989,18.109552,15.655413,13.508685,17.340289,16.861731,...,14.046464,13.837462,20.055209,20.336005,20.591114,16.804792,15.472431,17.583860,15.692518,16.754717
min,1.570000,53.070000,43.000000,51.000000,6.000000,5.000000,8.000000,10.570000,3.750000,5.140000,...,8.000000,9.000000,5.000000,6.000000,5.000000,1.000000,2.000000,3.260000,2.000000,2.000000
25%,1.780000,72.120000,62.820000,68.000000,43.440000,32.440000,49.097500,55.620000,33.250000,49.110000,...,47.330000,44.850000,25.000000,29.000000,25.440000,7.770000,9.500000,11.000000,9.437500,9.380000
50%,1.830000,76.200000,66.720000,72.000000,56.300000,49.855000,58.805000,63.000000,49.300000,61.100000,...,57.730000,55.000000,50.000000,55.190000,52.165000,10.140000,12.500000,16.280000,12.500000,12.460000
75%,1.850000,81.190000,70.952500,76.000000,64.710000,63.060000,66.750000,69.007500,60.737500,68.782500,...,66.000000,63.930000,64.200000,67.000000,65.120000,13.000000,15.390000,27.302500,15.422500,15.380000
max,2.080000,110.220000,92.190000,95.230000,89.360000,92.230000,93.110000,95.180000,90.790000,96.460000,...,95.680000,92.000000,90.670000,90.200000,94.370000,89.860000,86.880000,89.000000,91.620000,90.950000

In [37]:
match_df.describe()

              stage  home team goal  away team goal    total goal
count  25979.000000    25979.000000    25979.000000  25979.000000
mean      18.242773        1.544594        1.160938      2.705531
std       10.407354        1.297158        1.142110      1.672456
min        1.000000        0.000000        0.000000      0.000000
25%        9.000000        1.000000        0.000000      2.000000
50%       18.000000        1.000000        1.000000      3.000000
75%       27.000000        2.000000        2.000000      4.000000
max       38.000000       10.000000        9.000000     12.000000

In [38]:
team_df.describe()

,buildUpPlaySpeed,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth
count,288.000000,288.000000,288.000000,288.000000,288.000000,288.000000,288.000000,288.000000
mean,52.026458,48.725000,51.726736,53.401493,53.884792,45.821250,49.153403,52.044167
std,7.742841,7.351824,6.608335,7.544098,6.239400,6.999462,6.186604,6.421537
min,29.330000,30.000000,30.000000,33.330000,36.670000,25.670000,30.000000,30.000000
25%,47.297500,44.000000,48.000000,49.297500,50.200000,41.297500,45.600000,48.230000
50%,52.330000,48.450000,51.450000,53.635000,53.915000,46.000000,48.735000,52.450000
75%,57.347500,53.170000,55.702500,58.542500,58.000000,50.042500,52.830000,55.872500
max,72.500000,77.000000,68.830000,77.000000,70.000000,70.000000,70.000000,70.000000

In [42]:
import string

string.ascii_letters + string.digits

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

Estos son los caracteres normales, de los cuales ahora vamos a quitar los caracteres de las columnas de los datasets que no entran en ese conjunto

In [43]:
team_df.columns[~team_df.columns.str.match(r'^(\w+)$')]

Index(['team long name', 'team short name'], dtype='object')

team long name y team short name tienen nombres con espacios. Los vamos a quitar reemplazandolos con algun valor.

In [44]:
team_df.rename(columns={'team long name':'teamLongName', 'team short name':'teamShortName', }, inplace=True)

In [45]:
team_df.columns

Index(['teamLongName', 'teamShortName', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribblingClass',
       'buildUpPlayPassing', 'buildUpPlayPassingClass',
       'buildUpPlayPositioningClass', 'chanceCreationPassing',
       'chanceCreationPassingClass', 'chanceCreationCrossing',
       'chanceCreationCrossingClass', 'chanceCreationShooting',
       'chanceCreationShootingClass', 'chanceCreationPositioningClass',
       'defencePressure', 'defencePressureClass', 'defenceAggression',
       'defenceAggressionClass', 'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')

Reemplazamos las columnas quitando los espacios y nombrandolas con Camelcase

In [48]:
match_df.columns[~match_df.columns.str.match(r'^(\w+)$')]

Index(['country name', 'league name', 'home team long name',
       'home short long name', 'away team long name', 'away short long name',
       'home team goal', 'away team goal', 'total goal'],
      dtype='object')

In [49]:
match_df.columns = match_df.columns.str.replace(' ', '_')
match_df.columns

Index(['country_name', 'league_name', 'season', 'stage', 'date',
       'home_team_long_name', 'home_short_long_name', 'away_team_long_name',
       'away_short_long_name', 'home_team_goal', 'away_team_goal',
       'total_goal', 'Fecha'],
      dtype='object')

Reemplazamos los espacios en esta oportunidad con '_'

In [47]:
player_df.columns[~player_df.columns.str.match(r'^(\w+)$')]

Index(['player name', 'preferred foot', 'heading accuracy', 'short passing',
       'free kick accuracy', 'long passing', 'ball control', 'sprint speed',
       'shot power', 'long shots', 'standing tackle', 'sliding tackle'],
      dtype='object')

In [50]:
player_df.columns = player_df.columns.str.replace(' ', '_')
player_df.columns

Index(['player_name', 'birthday', 'height_m', 'weight_kg', 'overall_rating',
       'potential', 'preferred_foot', 'crossing', 'finishing',
       'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve',
       'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration',
       'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power',
       'jumping', 'stamina', 'strength', 'long_shots', 'aggression',
       'interceptions', 'positioning', 'vision', 'penalties', 'marking',
       'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling',
       'gk_kicking', 'gk_positioning', 'gk_reflexes'],
      dtype='object')

# 3. Agregar nuevas caracteristicas

Agregar al Dataframe `player_df` una nueva columna que sea `imc` correspondiente al **Indice de Masa Corporal**

Link:
* https://www.texasheart.org/heart-health/heart-information-center/topics/calculadora-del-indice-de-masa-corporal-imc/

In [67]:
def imc(peso,altura):
    return peso / (altura**2)

player_df['IMC'] = player_df.apply(lambda x: imc(x.weight_kg, x.height_m), axis=1)

In [68]:
player_df[['height_m','weight_kg','IMC']]

       height_m  weight_kg        IMC
0          1.83      84.82  25.327720
1          1.70      66.22  22.913495
2          1.70      73.94  25.584775
3          1.83      89.81  26.817761
4          1.83      69.85  20.857595
5          1.83      73.03  21.807161
6          1.73      66.22  22.125697
7          1.65      63.05  23.158861
8          1.90      82.10  22.742382
9          1.75      77.11  25.178776
10         1.83      82.10  24.515513
11         1.75      68.04  22.217143
12         1.88      76.20  21.559529
13         1.70      64.86  22.442907
14         1.78      69.85  22.045828
15         1.73      73.94  24.705135
16         1.83      79.83  23.837678
17         1.90      72.12  19.977839
18         1.75      68.04  22.217143
19         1.88      83.91  23.740946
20         1.78      73.03  23.049489
21         1.85      73.03  21.338203
22         1.80      73.03  22.540123
23         1.83      78.02  23.297202
24         1.80      73.03  22.540123
25         1.73      64.86  21.671289
26         1.85      74.84  21.867056
27         1.80      72.12  22.259259
28         1.83      77.11  23.025471
29         1.78      71.21  22.475066
...         ...        ...        ...
11030      1.75      73.03  23.846531
11031      1.80      74.84  23.098765
11032      1.75      66.22  21.622857
11033      1.78      64.86  20.470900
11034      1.80      77.11  23.799383
11035      1.73      69.85  23.338568
11036      1.85      73.94  21.604091
11037      1.98      92.99  23.719518
11038      1.80      73.94  22.820988
11039      1.75      67.13  21.920000
11040      1.83      78.93  23.568933
11041      1.96      94.80  24.677218
11042      1.85      79.83  23.325055
11043      1.83      77.11  23.025471
11044      1.88      83.01  23.486306
11045      1.73      68.95  23.037856
11046      1.65      64.86  23.823691
11047      1.83      74.84  22.347637
11048      1.75      67.13  21.920000
11049      1.83      79.83  23.837678
11050      1.88      74.84  21.174740
11051      1.90      81.19  22.490305
11052      1.70      71.21  24.640138
11053      1.80      72.12  22.259259
11054      1.90      78.02  21.612188
11055      1.83      76.20  22.753740
11056      1.83      79.83  23.837678
11057      1.80      69.85  21.558642
11058      1.85      78.02  22.796202
11059      1.80      79.83  24.638889

[11060 rows x 3 columns]

In [66]:
player_df.describe()

,height_m,weight_kg,overall_rating,potential,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,...,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,col_3,IMC
count,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,10582.000000,11060.000000,...,11060.000000,11060.000000,10582.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000,11060.000000
mean,1.817847,76.375393,66.821222,72.090216,52.853855,47.862155,56.100191,60.367143,47.110973,56.892354,...,46.231480,49.440716,47.124626,14.911413,16.676659,23.015325,16.750476,17.055242,139.168414,23.086261
std,0.063278,6.799564,6.237719,5.800313,16.169989,18.109552,15.655413,13.508685,17.340289,16.861731,...,20.055209,20.336005,20.591114,16.804792,15.472431,17.583860,15.692518,16.754717,16.403700,1.319189
min,1.570000,53.070000,43.000000,51.000000,6.000000,5.000000,8.000000,10.570000,3.750000,5.140000,...,5.000000,6.000000,5.000000,1.000000,2.000000,3.260000,2.000000,2.000000,83.319900,17.581485
25%,1.780000,72.120000,62.820000,68.000000,43.440000,32.440000,49.097500,55.620000,33.250000,49.110000,...,25.000000,29.000000,25.440000,7.770000,9.500000,11.000000,9.437500,9.380000,127.825500,22.259259
50%,1.830000,76.200000,66.720000,72.000000,56.300000,49.855000,58.805000,63.000000,49.300000,61.100000,...,50.000000,55.190000,52.165000,10.140000,12.500000,16.280000,12.500000,12.460000,138.798000,23.062089
75%,1.850000,81.190000,70.952500,76.000000,64.710000,63.060000,66.750000,69.007500,60.737500,68.782500,...,64.200000,67.000000,65.120000,13.000000,15.390000,27.302500,15.422500,15.380000,150.080400,23.872576
max,2.080000,110.220000,92.190000,95.230000,89.360000,92.230000,93.110000,95.180000,90.790000,96.460000,...,90.670000,90.200000,94.370000,89.860000,86.880000,89.000000,91.620000,90.950000,229.257600,30.766147

# 4. Tratar valores faltantes

Veamos cuantos valores nulos tenemos

In [69]:
player_missing_values_count = player_df.isnull().sum()

player_missing_values_count[player_missing_values_count > 0]

volleys           478
curve             478
agility           478
balance           478
jumping           478
vision            478
sliding_tackle    478
dtype: int64

In [70]:
team_missing_values_count = team_df.isnull().sum()

team_missing_values_count[team_missing_values_count > 0]

Series([], dtype: int64)

In [71]:
match_missing_values_count = match_df.isnull().sum()

match_missing_values_count[match_missing_values_count > 0]

Series([], dtype: int64)

Algunas tecnicas para tratar los _missing values_:
* **Eliminar** muestras o variables que tienen datos faltantes.
* **Imputar** los valores perdidos, es decir, sustituirlos por estimaciones por ejemplo la `media`, la `moda` ó usando `KNN`.

A) Analizar si es conveniente **Eliminar** las muestras o variables con datos faltantes del Dataframe `player_df`. 

B) Aplicar la **Imputacion** usando la `media` o `moda` sobre las columnas con _missing values_ del Dataframe `player_df`.

**Hint**:
* Para la imputacion usando la `media`, `moda` ver el siguiente link:  
    https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html

### ¿Eliminar los _missing values_? Justificar

In [72]:
len(player_df.dropna())/len(player_df)

0.9567811934900543

In [76]:
len(player_df.dropna(subset=['volleys']))/len(player_df)

0.9567811934900543

In [80]:
player_df.shape

(11060, 42)

In [83]:
player_df[player_df.volleys.isnull()]

,player_name,birthday,height_m,weight_kg,overall_rating,potential,preferred_foot,crossing,finishing,heading_accuracy,...,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,col_3,IMC
25,Abdelmajid Oulmers,1978-09-12,1.73,64.86,68.80,69.40,right,60.00,50.00,62.00,...,56.00,54.00,NaN,7.00,17.40,62.00,18.40,17.00,112.2078,21.671289
30,Abdeslam Ouaddou,1978-11-01,1.90,82.10,76.60,78.60,right,67.20,34.00,78.00,...,80.40,76.60,NaN,5.00,20.40,75.00,20.40,19.80,155.9900,22.742382
31,Abdessalam Benjelloun,1985-01-28,1.88,81.19,63.33,71.33,right,42.00,66.17,41.50,...,22.00,27.00,NaN,7.00,17.67,35.00,17.83,17.33,152.6372,22.971367
83,Aco Stojkov,1983-04-29,1.78,74.84,59.67,62.67,right,59.67,57.67,62.67,...,23.00,27.67,NaN,12.00,23.00,38.67,23.00,23.00,133.2152,23.620755
85,Adailton,1977-01-24,1.75,73.03,71.83,74.00,left,54.67,74.50,62.17,...,21.00,53.00,NaN,9.00,19.17,53.17,20.67,20.83,127.8025,23.846531
175,Adrian Paluchowski,1987-08-19,1.80,74.84,55.00,60.50,right,43.00,57.00,49.00,...,22.00,28.00,NaN,3.00,22.00,48.00,22.00,22.00,134.7120,23.098765
190,Adriano,1982-01-21,1.75,76.20,68.75,74.00,right,52.00,71.00,67.00,...,21.00,22.00,NaN,9.00,21.00,53.00,21.00,21.00,133.3500,24.881633
203,"Afonso Alves,24",1981-01-30,1.85,73.94,80.29,85.29,right,60.43,83.57,73.57,...,25.00,23.71,NaN,8.00,19.86,56.00,19.57,20.00,136.7890,21.604091
253,Alan Haydock,1976-01-13,1.75,72.12,63.33,65.67,right,60.00,43.00,62.67,...,55.00,64.00,NaN,13.00,20.00,63.67,20.33,20.00,126.2100,23.549388
275,Albert Baning,1985-03-19,1.93,81.19,65.00,78.00,right,35.00,30.00,56.60,...,62.00,70.00,NaN,9.00,17.60,62.20,17.80,17.60,156.6967,21.796558
289,Alberto Fontana,1967-01-23,1.85,73.03,76.00,77.25,right,22.00,28.00,37.00,...,24.00,27.00,NaN,73.50,78.50,73.50,75.00,76.50,135.1055,21.338203
343,Aleksandar Mitreski,1980-08-05,1.85,74.84,68.20,73.20,right,54.60,25.60,68.60,...,70.60,61.40,NaN,11.00,17.00,57.60,17.40,18.60,138.4540,21.867056
379,Alessandro Grandoni,1977-07-22,1.80,76.20,76.00,78.75,right,62.75,52.50,82.00,...,80.25,81.50,NaN,13.50,18.75,78.00,16.25,16.50,137.1600,23.518519
405,Alex Bruno,1982-05-09,1.88,86.18,69.80,75.40,right,30.60,35.40,71.80,...,70.60,70.80,NaN,12.60,18.20,52.20,18.20,19.00,162.0184,24.383205
456,Alexander Laas,1984-05-05,1.73,69.85,70.33,77.00,left,75.00,58.00,61.00,...,45.00,50.00,NaN,13.00,22.00,69.00,22.00,22.00,120.8405,23.338568
476,Alexandre Di Gregorio,1980-02-12,1.75,79.83,58.33,61.00,right,55.00,54.00,49.00,...,25.00,25.00,NaN,11.00,25.00,30.00,25.00,25.00,139.7025,26.066939
485,Alexandre Quennoz,1978-09-21,1.80,79.83,61.67,72.00,right,45.33,23.33,61.33,...,63.33,61.33,NaN,14.00,20.00,53.33,20.00,20.00,143.6940,24.638889
534,Allan Russell,1980-12-13,1.85,77.11,63.00,67.00,right,48.00,67.00,63.00,...,23.00,23.00,NaN,14.00,23.00,52.00,23.00,23.00,142.6535,22.530314
577,Amadou Alassane,1983-04-07,1.88,76.20,60.50,72.00,right,38.25,61.50,70.00,...,20.00,20.00,NaN,4.00,20.00,37.25,20.00,20.00,143.2560,21.559529
584,Amdy Faye,1977-03-12,1.83,78.02,73.20,75.80,right,55.40,51.00,74.40,...,75.40,74.60,NaN,9.00,19.60,64.20,20.40,20.00,142.7766,23.297202
655,Andre Leone,1979-02-12,1.83,81.19,71.80,81.00,left,23.00,27.00,78.00,...,75.60,75.20,NaN,14.00,19.60,33.00,20.00,18.80,148.5777,24.243782
675,Andrea Ardito,1977-01-08,1.73,60.78,71.00,77.00,left,69.00,58.00,69.00,...,72.00,74.50,NaN,6.00,18.50,72.50,17.00,16.50,105.1494,20.308062
713,Andrea Zanchetta,1975-02-02,1.80,73.94,76.00,80.00,right,70.00,64.50,77.50,...,70.50,63.00,NaN,11.00,18.75,75.00,18.25,18.75,133.0920,22.820988
756,Andrew McNeil,1987-01-19,1.80,83.01,61.50,67.50,right,21.00,21.00,21.00,...,21.00,21.00,NaN,67.50,61.00,58.00,64.00,66.50,149.4180,25.620370
774,Andriy Shevchenko,1976-09-29,1.83,72.12,81.20,89.80,right,70.60,85.20,80.00,...,21.80,31.00,NaN,8.80,20.40,46.40,20.80,20.60,131.9796,21.535430
798,Angel Manuel Vivar Dorado,1974-02-12,1.83,78.02,71.80,78.60,right,66.00,61.40,64.00,...,43.00,67.00,NaN,10.00,18.60,70.80,19.80,19.20,142.7766,23.297202
804,Angelo Martha,1982-04-29,1.85,82.10,60.67,64.00,right,33.00,31.00,62.00,...,59.67,62.67,NaN,6.00,21.00,47.00,17.67,18.67,151.8850,23.988313
827,Anthony Bentem,1990-03-19,1.80,74.84,56.33,66.67,right,34.00,24.00,45.00,...,56.67,48.33,NaN,7.00,23.00,46.00,23.00,23.00,134.7120,23.098765
885,Antonio Carlos Dos Santos,1979-10-03,1.88,68.04,70.60,79.00,left,68.80,45.80,62.80,...,65.60,62.80,NaN,5.00,17.20,72.40,17.00,16.80,127.9152,19.250792
887,Antonio Chimenti,1970-06-30,1.83,83.01,71.50,78.00,right,19.83,22.00,22.83,...,23.67,23.67,NaN,68.33,71.33,76.33,73.67,72.83,151.9083,24.787244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10449,Tony Heurtebis,1975-01-15,1.80,73.03,66.60,75.00,right,28.40,22.00,22.00,...,22.00,29.80,NaN,64.80,63.80,59.00,71.40,68.80,131.4540,22.540123
10475,Tugay Kerimoglou,1970-08-24,1.75,73.03,73.00,81.50,right,64.00,43.00,61.50,...,61.00,67.50,NaN,5.00,17.75,89.00,18.50,19.75,127.8025,23.846531
10499,Ulrich Le-Pen,1974-01-23,1.75,68.04,71.60,78.60,left,74.20,69.80,62.60,...,27.00,40.00,NaN,9.00,18.60,77.20,19.60,18.60,119.0700,22.217143
10504,Umit Ozat,1976-10-30,1.85,73.94,71.33,76.00,left,82.00,32.00,68.00,...,78.00,69.00,NaN,13.00,17.33,73.00,18.00,19.33,136.7890,21.604091
10528,Vahid Hashemian,1976-07-21,1.83,78.02,72.40,78.20,right,54.80,77.00,83.60,...,28.00,21.60,NaN,14.00,20.20,23.00,19.80,19.00,142.7766,23.297202
10545,Valerien Ismael,1975-09-28,1.90,83.01,79.60,85.20,right,50.00,47.00,83.60,...,80.40,82.80,NaN,7.00,21.40,66.60,22.60,22.80,157.7190,22.994460
10575,Veldin Muharemovic,1984-12-06,1.83,77.11,54.33,60.00,right,49.00,39.67,40.00,...,56.00,60.00,NaN,1.00,21.00,49.00,21.00,21.00,141.1113,23.025471
10627,Vincent Hognon,1974-08-16,1.83,74.84,75.00,75.67,right,33.00,25.00,79.33,...,79.33,76.33,NaN,11.00,18.00,59.67,17.33,16.67,136.9572,22.347637
10640,Vincent Provoost,1984-02-07,1.78,76.20,58.75,63.50,right,46.00,36.00,56.50,...,53.00,60.00,NaN,10.00,21.00,49.50,21.00,21.00,135.6360,24.049994
10670,Vitor Lima,1981-08-18,1.78,63.96,62.00,64.00,right,46.00,46.00,53.00,...,60.00,68.00,NaN,6.00,22.00,59.00,22.00,22.00,113.8488,20.186845
10671,Vitor Moreno,1980-11-29,1.80,86.18,58.50,62.00,right,52.00,48.00,55.00,...,51.75,52.50,NaN,6.00,20.00,47.00,20.00,20.00,155.1240,26.598765
10674,Vittorio Villano,1988-02-02,1.65,62.14,51.67,74.00,right,48.67,39.00,37.00,...,28.00,32.00,NaN,2.00,21.00,51.00,21.00,21.00,102.5310,22.824610
10684,Vladimir Stojkovic,1983-07-28,1.93,93.89,75.75,83.50,right,19.00,19.50,19.00,...,18.50,18.50,NaN,77.75,72.75,73.50,74.00,82.00,181.2077,25.206046
10692,Vojtech Schulmeister,1983-09-09,1.83,78.93,59.40,66.60,left,43.80,63.20,61.20,...,32.00,33.00,NaN,13.00,20.00,52.80,20.00,20.00,144.4419,23.568933
10696,Vukasin Devic,1984-03-15,1.85,74.84,65.50,70.00,right,32.00,40.00,66.00,...,66.25,67.00,NaN,5.00,20.00,49.00,20.00,20.00,138.4540,21.867056
10711,Walid Regragui,1975-09-23,1.78,66.22,67.00,73.00,right,73.00,56.00,66.00,...,67.00,68.00,NaN,6.00,22.00,72.00,22.00,22.00,117.8716,20.900139
10738,Wellington,1985-08-17,1.75,71.21,63.86,74.57,left,67.57,32.86,51.57,...,63.29,63.71,NaN,10.29,19.00,53.86,19.43,18.86,124.6175,23.252245
10742,Wender,1975-04-17,1.78,73.94,72.33,75.33,left,74.00,67.00,58.00,...,34.00,42.00,NaN,9.00,17.33,60.33,18.67,18.00,131.6132,23.336700
10757,Wesllem,1985-04-21,1.75,72.12,63.33,68.00,right,54.00,59.33,60.00,...,23.00,22.00,NaN,6.00,23.00,45.00,23.00,23.00,126.2100,23.549388
10802,Willy Grondin,1974-10-12,1.78,78.02,57.40,77.00,right,20.00,18.60,18.20,...,18.20,18.60,NaN,57.00,55.00,59.00,61.00,56.00,138.8756,24.624416
10894,Yasin Karaca,1983-12-16,1.70,67.13,61.00,63.00,right,62.00,56.00,33.00,...,21.00,22.00,NaN,5.00,22.00,60.00,22.00,22.00,114.1210,23.228374
10909,"Yazid Mansouri,30",1978-02-25,1.75,68.95,69.80,72.00,right,63.00,55.40,70.80,...,68.40,62.00,NaN,8.20,18.80,69.60,18.80,18.60,120.6625,22.514286
10913,Yildiray Basturk,1978-12-24,1.70,68.95,78.50,82.67,right,78.67,60.33,37.83,...,21.00,37.17,NaN,6.00,19.00,78.33,18.67,18.50,117.2150,23.858131
10924,Yoav Ziv,1981-03-16,1.75,74.84,64.25,68.00,right,66.00,64.75,65.50,...,59.00,60.00,NaN,8.00,21.00,57.50,21.00,21.00,130.9700,24.437551
10934,"Yohan Lachor,29",1976-08-03,1.83,79.83,64.33,65.33,right,38.33,39.33,74.33,...,62.33,64.33,NaN,11.00,19.00,60.33,15.67,17.33,146.0889,23.837678
10949,Yoshito Okubo,1982-06-09,1.68,60.78,71.00,77.00,right,72.00,69.00,55.00,...,23.00,23.00,NaN,12.00,23.00,65.00,23.00,23.00,102.1104,21.534864
10978,Yuri Cornelisse,1975-05-08,1.83,78.02,64.00,71.25,left,63.00,62.00,68.00,...,31.50,32.50,NaN,15.00,21.00,61.50,21.00,21.00,142.7766,23.297202
11020,Ze Manuel,1975-02-22,1.68,64.86,72.67,74.83,right,72.50,68.17,51.50,...,41.00,36.00,NaN,8.00,20.17,67.00,20.83,20.67,108.9648,22.980442
11024,Ze Vitor,1982-02-11,1.75,73.94,61.60,64.80,right,39.60,60.60,60.60,...,52.60,53.60,NaN,10.00,20.00,49.60,20.00,20.00,129.3950,24.143673
11027,Zeljko Kalac,1972-12-16,2.03,94.80,72.50,80.50,right,30.00,29.00,38.00,...,21.00,35.50,NaN,76.25,72.00,73.75,72.50,73.75,192.4440,23.004683

In [94]:
player_df_nulos = player_df[player_df.volleys.isnull()]
player_df_nulos[['volleys','agility','curve','balance','jumping','vision','sliding_tackle']]

       volleys  agility  curve  balance  jumping  vision  sliding_tackle
25         NaN      NaN    NaN      NaN      NaN     NaN             NaN
30         NaN      NaN    NaN      NaN      NaN     NaN             NaN
31         NaN      NaN    NaN      NaN      NaN     NaN             NaN
83         NaN      NaN    NaN      NaN      NaN     NaN             NaN
85         NaN      NaN    NaN      NaN      NaN     NaN             NaN
175        NaN      NaN    NaN      NaN      NaN     NaN             NaN
190        NaN      NaN    NaN      NaN      NaN     NaN             NaN
203        NaN      NaN    NaN      NaN      NaN     NaN             NaN
253        NaN      NaN    NaN      NaN      NaN     NaN             NaN
275        NaN      NaN    NaN      NaN      NaN     NaN             NaN
289        NaN      NaN    NaN      NaN      NaN     NaN             NaN
343        NaN      NaN    NaN      NaN      NaN     NaN             NaN
379        NaN      NaN    NaN      NaN      NaN     NaN             NaN
405        NaN      NaN    NaN      NaN      NaN     NaN             NaN
456        NaN      NaN    NaN      NaN      NaN     NaN             NaN
476        NaN      NaN    NaN      NaN      NaN     NaN             NaN
485        NaN      NaN    NaN      NaN      NaN     NaN             NaN
534        NaN      NaN    NaN      NaN      NaN     NaN             NaN
577        NaN      NaN    NaN      NaN      NaN     NaN             NaN
584        NaN      NaN    NaN      NaN      NaN     NaN             NaN
655        NaN      NaN    NaN      NaN      NaN     NaN             NaN
675        NaN      NaN    NaN      NaN      NaN     NaN             NaN
713        NaN      NaN    NaN      NaN      NaN     NaN             NaN
756        NaN      NaN    NaN      NaN      NaN     NaN             NaN
774        NaN      NaN    NaN      NaN      NaN     NaN             NaN
798        NaN      NaN    NaN      NaN      NaN     NaN             NaN
804        NaN      NaN    NaN      NaN      NaN     NaN             NaN
827        NaN      NaN    NaN      NaN      NaN     NaN             NaN
885        NaN      NaN    NaN      NaN      NaN     NaN             NaN
887        NaN      NaN    NaN      NaN      NaN     NaN             NaN
...        ...      ...    ...      ...      ...     ...             ...
10449      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10475      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10499      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10504      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10528      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10545      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10575      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10627      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10640      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10670      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10671      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10674      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10684      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10692      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10696      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10711      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10738      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10742      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10757      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10802      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10894      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10909      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10913      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10924      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10934      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10949      NaN      NaN    NaN      NaN      NaN     NaN             NaN
10978      NaN      NaN    NaN      NaN      NaN     NaN             NaN
11020      NaN      NaN    NaN      NaN      NaN     NaN             NaN
11024      NaN      NaN    NaN      NaN      NaN     NaN             NaN
11027      NaN      NaN    NaN      NaN      NaN     NaN             NaN

[478 rows x 7 columns]

In [95]:
player_df_nulos[['volleys','agility','curve','balance','jumping','vision','sliding_tackle']].dtypes

volleys           float64
agility           float64
curve             float64
balance           float64
jumping           float64
vision            float64
sliding_tackle    float64
dtype: object

Como podremos observar de los 478 NaN q se encuentran en el dataset, todas las columnas presentan el mismo valor para los mismos jugadores. Es posible de eliminar dichos jugadores que no contengan esta información ya que tenemos 11060 muestras para continuar con nuestro analisis.

In [89]:
player_df_sinNulos = player_df.dropna()
player_df_sinNulos.shape

(10582, 42)

In [91]:
player_df.dtypes

player_name            object
birthday               object
height_m              float64
weight_kg             float64
overall_rating        float64
potential             float64
preferred_foot         object
crossing              float64
finishing             float64
heading_accuracy      float64
short_passing         float64
volleys               float64
dribbling             float64
curve                 float64
free_kick_accuracy    float64
long_passing          float64
ball_control          float64
acceleration          float64
sprint_speed          float64
agility               float64
reactions             float64
balance               float64
shot_power            float64
jumping               float64
stamina               float64
strength              float64
long_shots            float64
aggression            float64
interceptions         float64
positioning           float64
vision                float64
penalties             float64
marking               float64
standing_tackle       float64
sliding_tackle        float64
gk_diving             float64
gk_handling           float64
gk_kicking            float64
gk_positioning        float64
gk_reflexes           float64
col_3                 float64
IMC                   float64
dtype: object

In [92]:
del player_df['col_3']
del player_df_sinNulos['col_3']

In [93]:
player_df.dtypes

player_name            object
birthday               object
height_m              float64
weight_kg             float64
overall_rating        float64
potential             float64
preferred_foot         object
crossing              float64
finishing             float64
heading_accuracy      float64
short_passing         float64
volleys               float64
dribbling             float64
curve                 float64
free_kick_accuracy    float64
long_passing          float64
ball_control          float64
acceleration          float64
sprint_speed          float64
agility               float64
reactions             float64
balance               float64
shot_power            float64
jumping               float64
stamina               float64
strength              float64
long_shots            float64
aggression            float64
interceptions         float64
positioning           float64
vision                float64
penalties             float64
marking               float64
standing_tackle       float64
sliding_tackle        float64
gk_diving             float64
gk_handling           float64
gk_kicking            float64
gk_positioning        float64
gk_reflexes           float64
IMC                   float64
dtype: object

### Imputacion usando Media y Moda

In [97]:
player_df[['volleys','agility','curve','balance','jumping','vision','sliding_tackle']].describe()

,volleys,agility,curve,balance,jumping,vision,sliding_tackle
count,10582.000000,10582.000000,10582.000000,10582.000000,10582.000000,10582.000000,10582.000000
mean,47.110973,64.409834,50.423617,64.475489,66.038396,55.866959,47.124626
std,17.340289,12.166882,17.309270,11.262069,9.555309,14.046464,20.591114
min,3.750000,21.000000,5.710000,20.000000,21.000000,8.000000,5.000000
25%,33.250000,57.000000,38.760000,58.160000,60.000000,47.330000,25.440000
50%,49.300000,65.730000,52.565000,65.670000,66.890000,57.730000,52.165000
75%,60.737500,73.000000,63.570000,72.000000,72.360000,66.000000,65.120000
max,90.790000,94.670000,92.570000,94.310000,94.310000,95.680000,94.370000

In [99]:
player_df.mode()

,player_name,birthday,height_m,weight_kg,overall_rating,potential,preferred_foot,crossing,finishing,heading_accuracy,...,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,IMC
0,Danilo,1989-03-02,1.83,74.84,64.0,67.0,right,49.0,25.0,52.0,...,45.0,25.0,25.0,25.0,9.0,14.0,9.0,11.0,12.0,22.347637

In [107]:
player_df_reemplazo_nan_moda = player_df

for column in ['volleys','agility','curve','balance','jumping','vision','sliding_tackle']:
    player_df_reemplazo_nan_moda[column].fillna(player_df_reemplazo_nan_moda[column].mode()[0], inplace=True)

player_df_reemplazo_nan_moda

,player_name,birthday,height_m,weight_kg,overall_rating,potential,preferred_foot,crossing,finishing,heading_accuracy,...,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,IMC
0,Aaron Appindangoye,1992-02-29,1.83,84.82,63.60,67.60,right,48.60,43.60,70.60,...,47.60,63.80,66.00,67.80,5.60,10.60,9.60,7.60,7.60,25.327720
1,Aaron Cresswell,1989-12-15,1.70,66.22,66.97,74.48,left,70.79,49.45,52.94,...,53.12,69.39,68.79,71.52,12.18,8.67,14.24,10.36,12.91,22.913495
2,Aaron Doran,1991-05-13,1.70,73.94,67.00,74.19,right,68.12,57.92,58.69,...,60.54,22.04,21.12,21.35,14.04,11.81,17.73,10.12,13.50,25.584775
3,Aaron Galindo,1982-05-08,1.83,89.81,69.09,70.78,right,57.22,26.26,69.26,...,41.74,70.61,70.65,68.04,14.17,11.17,22.87,11.17,10.17,26.817761
4,Aaron Hughes,1979-11-08,1.83,69.85,73.24,74.68,right,45.08,38.84,73.04,...,52.96,77.60,76.04,74.60,8.28,8.32,24.92,12.84,11.92,20.857595
5,Aaron Hunt,1986-09-04,1.83,73.03,77.26,80.15,left,73.89,72.81,65.52,...,75.59,31.70,31.52,32.33,13.22,12.41,15.07,15.56,14.85,21.807161
6,Aaron Kuhl,1996-01-30,1.73,66.22,60.57,76.00,right,47.57,31.57,46.57,...,41.57,51.57,57.14,56.57,7.57,12.57,13.57,13.57,14.57,22.125697
7,Aaron Lennon,1987-04-16,1.65,63.05,79.77,82.00,right,78.04,65.96,30.46,...,63.46,23.23,26.15,20.88,12.85,9.81,17.88,16.92,13.12,23.158861
8,Aaron Lennox,1993-02-19,1.90,82.10,48.00,56.86,right,12.00,15.00,16.00,...,41.00,15.00,15.00,12.00,53.00,41.00,39.00,51.00,53.00,22.742382
9,Aaron Meijers,1987-10-28,1.75,77.11,67.05,69.42,left,63.89,46.05,56.84,...,54.42,62.58,64.58,61.74,6.21,14.21,6.21,9.21,14.21,25.178776
10,Aaron Mokoena,1980-11-25,1.83,82.10,71.62,76.00,right,26.00,56.12,79.75,...,51.50,72.88,77.00,75.38,6.50,12.50,43.00,17.25,16.62,24.515513
11,Aaron Mooy,1990-09-15,1.75,68.04,66.29,73.14,right,66.57,61.21,43.46,...,60.04,48.79,52.71,45.07,10.29,7.29,11.29,10.29,11.29,22.217143
12,Aaron Muirhead,1990-08-30,1.88,76.20,62.25,70.00,right,48.00,23.00,65.00,...,74.00,58.50,61.50,55.00,8.00,11.00,6.00,6.00,7.00,21.559529
13,Aaron Niguez,1989-04-26,1.70,64.86,66.93,75.30,left,59.56,66.22,53.89,...,61.93,32.41,28.89,36.00,12.96,14.00,15.56,15.63,11.56,22.442907
14,Aaron Ramsey,1990-12-26,1.78,69.85,78.50,84.68,right,72.88,70.92,56.75,...,75.18,59.30,68.92,64.15,6.25,12.25,13.38,11.38,9.62,22.045828
15,Aaron Splaine,1996-10-13,1.73,73.94,54.62,62.62,left,54.38,51.38,42.38,...,54.38,42.38,46.38,44.38,10.38,12.38,7.38,13.38,8.38,24.705135
16,Aaron Taylor-Sinclair,1991-04-08,1.83,79.83,62.61,69.50,left,59.61,23.83,58.39,...,39.39,58.67,62.50,60.56,8.39,10.39,11.39,7.39,8.39,23.837678
17,Aaron Wilbraham,1979-10-21,1.90,72.12,61.77,64.14,right,47.36,64.45,72.86,...,66.45,23.55,21.45,20.41,15.32,17.09,18.68,15.59,16.27,19.977839
18,Aatif Chahechouhe,1986-07-02,1.75,68.04,69.38,74.50,right,69.50,78.00,57.19,...,73.19,25.44,26.44,23.44,6.44,9.44,7.44,14.44,9.44,22.217143
19,Abasse Ba,1976-07-12,1.88,83.91,65.60,70.60,right,41.00,33.00,73.20,...,53.60,65.20,62.00,57.00,7.80,16.60,38.60,16.60,16.40,23.740946
20,Abdelaziz Barrada,1989-06-19,1.78,73.03,71.86,78.86,right,70.21,58.36,50.36,...,62.50,34.36,41.36,32.36,10.36,6.36,5.36,15.36,6.36,23.049489
21,Abdelfettah Boukhriss,1986-10-22,1.85,73.03,64.00,69.00,left,47.00,29.00,65.00,...,42.00,64.00,65.00,62.00,11.00,5.00,15.00,10.00,10.00,21.338203
22,Abdelhamid El Kaoutari,1990-03-17,1.80,73.03,68.29,73.57,left,61.14,20.05,62.33,...,31.10,68.86,69.10,72.10,7.76,11.90,14.62,9.33,10.19,22.540123
23,Abdelkader Ghezzal,1984-12-05,1.83,78.02,68.69,71.31,right,63.50,63.85,65.73,...,66.54,26.65,35.19,32.19,9.04,8.69,18.31,8.69,9.50,23.297202
24,Abdellah Zoubir,1991-12-05,1.80,73.03,59.00,69.00,right,49.00,56.00,47.00,...,58.00,36.00,32.00,30.00,7.00,14.00,14.00,13.00,14.00,22.540123
25,Abdelmajid Oulmers,1978-09-12,1.73,64.86,68.80,69.40,right,60.00,50.00,62.00,...,47.00,56.00,54.00,25.00,7.00,17.40,62.00,18.40,17.00,21.671289
26,Abdelmalek Cherrad,1981-01-14,1.85,74.84,61.60,73.00,right,49.00,64.00,63.40,...,57.80,30.00,34.00,36.00,11.40,17.40,23.00,17.80,18.60,21.867056
27,Abdelmalek El Hasnaoui,1994-02-09,1.80,72.12,63.00,72.00,left,42.00,52.00,39.00,...,46.00,32.00,33.00,40.00,8.00,13.00,8.00,15.00,8.00,22.259259
28,Abdelouahed Chakhsi,1986-10-01,1.83,77.11,54.33,59.50,right,53.00,34.33,48.00,...,45.00,51.17,58.33,53.00,10.00,7.00,8.00,11.00,10.00,23.025471
29,Abderrazak Jadid,1983-06-01,1.78,71.21,63.31,65.54,right,64.69,57.23,47.23,...,56.77,45.62,45.15,43.69,7.38,16.46,28.00,12.46,14.08,22.475066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11030,Zezinho,1992-09-23,1.75,73.03,69.00,82.00,right,53.00,63.00,63.00,...,64.00,68.00,70.00,67.00,14.00,12.00,5.00,14.00,6.00,23.846531
11031,Zhi Zheng,1980-08-20,1.80,74.84,70.43,70.14,right,70.00,67.86,66.00,...,67.57,54.57,57.57,60.00,13.71,17.14,50.43,15.29,16.71,23.098765
11032,Zhi-Gin Lam,1991-06-04,1.75,66.22,66.28,74.28,right,66.61,44.83,38.89,...,46.17,60.17,61.83,63.56,10.17,7.17,9.17,15.17,12.17,21.622857
11033,Zie Diabate,1989-03-02,1.78,64.86,62.61,67.50,left,54.83,26.28,54.28,...,46.28,63.44,67.17,65.22,12.17,8.17,10.17,11.17,13.17,20.470900
11034,Ziggy Gordon,1993-04-23,1.80,77.11,62.30,71.10,right,57.70,30.30,52.30,...,41.30,61.10,64.80,63.10,5.30,10.30,14.30,9.30,8.30,23.799383
11035,Ziguy Badibanga,1991-11-26,1.73,69.85,63.75,72.25,right,60.00,58.00,34.00,...,52.00,24.00,21.00,23.00,10.00,7.00,7.00,12.00,14.00,23.338568
11036,Zinedine Machach,1996-01-05,1.85,73.94,63.44,76.44,right,64.11,53.89,54.33,...,55.00,50.44,62.00,63.33,13.00,8.00,11.00,11.00,9.00,21.604091
11037,Zinho Gano,1993-10-13,1.98,92.99,62.73,70.47,left,48.93,63.80,66.40,...,58.53,21.27,28.53,20.20,11.53,12.53,7.53,10.53,8.53,23.719518
11038,Ziri Hammar,1992-07-25,1.80,73.94,64.18,72.64,right,67.00,60.00,59.00,...,60.00,21.00,19.55,19.09,13.00,11.00,15.00,7.00,14.00,22.820988
11039,Zizo,1996-01-10,1.75,67.13,60.40,72.40,right,41.00,44.00,36.40,...,53.00,38.00,42.00,39.00,12.00,5.00,7.00,11.00,8.00,21.920000
11040,Zlatan Bajramovic,1979-08-12,1.83,78.93,75.57,82.86,right,73.86,67.57,75.00,...,74.71,72.57,73.57,74.86,12.57,16.43,57.71,16.43,19.00,23.568933
11041,Zlatan Ibrahimovic,1981-10-03,1.96,94.80,88.29,90.05,right,72.38,90.00,79.71,...,88.00,20.90,43.81,26.81,12.67,17.14,24.71,13.24,15.14,24.677218
11042,Zlatan Ljubijankic,1983-12-15,1.85,79.83,70.35,73.10,right,68.80,68.70,71.25,...,61.15,35.60,46.40,49.60,7.25,17.75,27.70,9.50,10.70,23.325055
11043,Zlatko Dedic,1984-10-05,1.83,77.11,67.67,71.75,right,57.50,68.46,63.58,...,67.38,28.17,31.17,29.17,13.42,16.04,12.92,16.79,11.54,23.025471
11044,Zlatko Janjic,1986-05-07,1.88,83.01,64.54,65.85,right,63.31,67.15,62.31,...,72.15,19.00,27.08,18.00,11.00,14.00,15.77,7.00,16.00,23.486306
11045,Zlatko Junuzovic,1987-09-26,1.73,68.95,75.46,79.00,right,73.74,67.15,55.90,...,66.15,56.54,58.13,51.13,13.54,9.31,14.54,14.74,8.46,23.037856
11046,Zola Matumona,1981-11-26,1.65,64.86,66.00,66.14,left,64.71,57.57,46.00,...,67.00,31.00,32.00,31.00,11.00,10.57,19.86,5.43,9.57,23.823691
11047,Zoltan Gera,1979-04-22,1.83,74.84,74.42,76.65,right,81.92,73.46,70.04,...,72.23,37.77,46.62,35.77,11.23,13.00,24.46,9.35,10.85,22.347637
11048,Zoltan Stieber,1988-10-16,1.75,67.13,69.44,76.26,left,64.30,67.15,53.93,...,55.85,23.81,28.22,30.56,5.37,8.48,19.26,16.26,9.26,21.920000
11049,Zoltan Szelesi,1981-11-22,1.83,79.83,67.00,65.00,right,57.86,55.00,65.29,...,58.43,68.43,69.14,63.00,12.43,15.29,38.57,14.86,15.57,23.837678
11050,Zoran Josipovic,1995-08-25,1.88,74.84,59.55,72.55,right,28.00,59.64,66.00,...,54.00,50.00,49.00,48.00,5.00,10.00,8.00,9.00,14.00,21.174740
11051,Zoran Rendulic,1984-05-22,1.90,81.19,64.40,72.00,right,37.00,17.00,78.00,...,47.00,66.00,66.60,61.00,13.00,14.00,8.00,8.00,14.00,22.490305
11052,Zoran Tosic,1987-04-28,1.70,71.21,77.04,80.70,left,69.00,75.09,51.35,...,67.52,22.00,24.61,20.48,6.00,13.74,23.43,9.61,13.74,24.640138
11053,Zouhaier Dhaouadhi,1988-01-01,1.80,72.12,64.00,65.38,left,65.00,60.00,36.75,...,76.00,39.00,26.00,24.00,16.00,10.00,12.00,8.00,8.00,22.259259
11054,Zouhair Feddal,1989-01-01,1.90,78.02,65.76,69.38,left,47.52,29.57,68.48,...,36.62,69.38,72.43,58.43,12.62,13.62,11.62,9.62,7.62,21.612188
11055,Zoumana Camara,1979-04-03,1.83,76.20,74.38,75.46,right,42.00,27.00,75.15,...,55.54,78.77,76.31,72.69,12.85,12.77,25.46,11.38,13.62,22.753740
11056,Zsolt Laczko,1986-12-18,1.83,79.83,65.69,71.62,left,67.25,46.75,60.31,...,51.88,63.25,65.25,63.88,9.00,8.00,5.00,5.00,8.00,23.837678
11057,Zsolt Low,1979-04-29,1.80,69.85,67.57,72.86,left,63.14,44.57,59.86,...,61.00,61.00,64.29,59.00,7.14,18.71,42.43,16.71,16.71,21.558642
11058,Zurab Khizanishvili,1981-10-06,1.85,78.02,70.75,78.12,right,46.75,43.00,79.00,...,64.00,70.75,73.25,65.00,14.00,18.50,41.62,19.00,20.00,22.796202
11059,Zvjezdan Misimovic,1982-06-05,1.80,79.83,80.00,81.70,right,78.20,72.60,57.40,...,70.90,26.20,31.20,30.00,9.00,15.40,42.10,16.20,12.00,24.638889

In [109]:
player_df_reemplazo_nan_moda

player_missing_values_count = player_df_reemplazo_nan_moda.isnull().sum()

player_missing_values_count[player_missing_values_count > 0]

Series([], dtype: int64)

NO se puede calcular con moda porque los valores son decimales (float). No es entero el numero

# 5. Normalizacion de columnas

Primero que todo la notación:
* $x = [x_1, x_2, ..., x_n]$
* $\mu$: Media
* $\sigma$: Desviacion Estandar

Ahora normalizaremos algunas de las columnas del Dataframe, para ello usaremos dos tipos de normalizacion:

* Min-Max:  
$$
z_i = \frac{x_i - min(x)}{max(x) - min(x)}
$$
* Z-score
$$
z_i = \frac{x_i - \mu}{\sigma}
$$

Normalizar la columna `crossing` usando **Min-Max**.

Normalizar la columna `short_passing` usando **Z-score**.

**Hints**:
* https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html

### Min-Max

In [113]:
import pandas as pd
from sklearn import preprocessing

In [115]:
scaler = preprocessing.MinMaxScaler()
player_df[["crossing"]] = scaler.fit_transform(player_df[["crossing"]])
player_df[["crossing"]]

       crossing
0      0.511036
1      0.777231
2      0.745202
3      0.614443
4      0.468810
5      0.814419
6      0.498680
7      0.864203
8      0.071977
9      0.694458
10     0.239923
11     0.726607
12     0.503839
13     0.642514
14     0.802303
15     0.580374
16     0.643114
17     0.496161
18     0.761756
19     0.419866
20     0.770274
21     0.491843
22     0.661468
23     0.689779
24     0.515835
25     0.647793
26     0.515835
27     0.431862
28     0.563820
29     0.704055
...         ...
11030  0.563820
11031  0.767754
11032  0.727087
11033  0.585773
11034  0.620202
11035  0.647793
11036  0.697097
11037  0.514995
11038  0.731766
11039  0.419866
11040  0.814060
11041  0.796305
11042  0.753359
11043  0.617802
11044  0.687500
11045  0.812620
11046  0.704295
11047  0.910749
11048  0.699376
11049  0.622121
11050  0.263916
11051  0.371881
11052  0.755758
11053  0.707774
11054  0.498081
11055  0.431862
11056  0.734765
11057  0.685461
11058  0.488844
11059  0.866123

[11060 rows x 1 columns]

In [117]:
scaler = preprocessing.MinMaxScaler()
player_df_sinNulos[["crossing"]] = scaler.fit_transform(player_df_sinNulos[["crossing"]])
player_df_sinNulos[["crossing"]]

       crossing
0      0.511036
1      0.777231
2      0.745202
3      0.614443
4      0.468810
5      0.814419
6      0.498680
7      0.864203
8      0.071977
9      0.694458
10     0.239923
11     0.726607
12     0.503839
13     0.642514
14     0.802303
15     0.580374
16     0.643114
17     0.496161
18     0.761756
19     0.419866
20     0.770274
21     0.491843
22     0.661468
23     0.689779
24     0.515835
26     0.515835
27     0.431862
28     0.563820
29     0.704055
32     0.424664
...         ...
11030  0.563820
11031  0.767754
11032  0.727087
11033  0.585773
11034  0.620202
11035  0.647793
11036  0.697097
11037  0.514995
11038  0.731766
11039  0.419866
11040  0.814060
11041  0.796305
11042  0.753359
11043  0.617802
11044  0.687500
11045  0.812620
11046  0.704295
11047  0.910749
11048  0.699376
11049  0.622121
11050  0.263916
11051  0.371881
11052  0.755758
11053  0.707774
11054  0.498081
11055  0.431862
11056  0.734765
11057  0.685461
11058  0.488844
11059  0.866123

[10582 rows x 1 columns]

### Z-score

In [116]:
from scipy import stats
player_df['short_passing'] = stats.zscore(player_df['short_passing'])
player_df['short_passing']

0        0.017238
1        0.140868
2        0.351853
3        0.320761
4        0.325202
5        1.324605
6        0.237107
7        1.177285
8       -2.766282
9        0.635387
10       1.462300
11       0.760498
12      -0.175239
13      -0.164135
14       1.651816
15      -0.332182
16       0.108295
17      -0.316636
18       0.972223
19      -0.338105
20       0.565059
21      -0.249269
22       0.110516
23       0.428104
24      -0.323299
25       1.009238
26      -0.471358
27       0.268940
28      -0.273699
29       0.314838
           ...
11030    0.713118
11031    0.734587
11032    0.421441
11033   -0.253711
11034   -0.745269
11035   -0.073078
11036    0.680545
11037   -0.550570
11038    0.639089
11039    0.446611
11040    1.273524
11041    1.767303
11042    0.531745
11043    0.200832
11044    0.274862
11045    1.235028
11046    0.237107
11047    1.214300
11048    0.650193
11049    0.406635
11050   -0.915537
11051   -0.619418
11052    1.183208
11053    0.565059
11054   -0.115275
11055    0.713118
11056    0.203793
11057    0.480665
11058   -0.110093
11059    1.860580
Name: short_passing, Length: 11060, dtype: float64

# 6. Codificar variables

> Las variables categóricas deben ser etiquetadas como variables numéricas, no como cadenas.

Codificar la variable `country_name` del Dataframe `match_df`

In [120]:
from sklearn import preprocessing

match_df_codificados = match_df

le = preprocessing.LabelEncoder()
le.fit(match_df_codificados['country_name'])

dict(zip(le.classes_, le.transform(le.classes_)))

{'Belgium': 0,
 'England': 1,
 'France': 2,
 'Germany': 3,
 'Italy': 4,
 'Netherlands': 5,
 'Poland': 6,
 'Portugal': 7,
 'Scotland': 8,
 'Spain': 9,
 'Switzerland': 10}

In [121]:
match_df_codificados['country_name_codificado'] = le.transform(match_df_codificados['country_name']) 
match_df_codificados

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,Fecha,country_name_codificado
0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17 00:00:00,KRC Genk,GEN,Beerschot AC,BAC,1,1,2,2008-08-17,0
1,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,SV Zulte-Waregem,ZUL,Sporting Lokeren,LOK,0,0,0,2008-08-16,0
2,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KSV Cercle Brugge,CEB,RSC Anderlecht,AND,0,3,3,2008-08-16,0
3,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17 00:00:00,KAA Gent,GEN,RAEC Mons,MON,5,0,5,2008-08-17,0
4,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,FCV Dender EH,DEN,Standard de Liège,STL,1,3,4,2008-08-16,0
5,Belgium,Belgium Jupiler League,2008/2009,1,2008-09-24 00:00:00,KV Mechelen,MEC,Club Brugge KV,CLB,1,1,2,2008-09-24,0
6,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KSV Roeselare,ROS,KV Kortrijk,KOR,2,2,4,2008-08-16,0
7,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,Tubize,TUB,Royal Excel Mouscron,MOU,1,2,3,2008-08-16,0
8,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KVC Westerlo,WES,Sporting Charleroi,CHA,1,0,1,2008-08-16,0
9,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Club Brugge KV,CLB,KV Kortrijk,KOR,4,1,5,2008-11-01,0
10,Belgium,Belgium Jupiler League,2008/2009,10,2008-10-31 00:00:00,Standard de Liège,STL,Sporting Charleroi,CHA,1,2,3,2008-10-31,0
11,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02 00:00:00,SV Zulte-Waregem,ZUL,KAA Gent,GEN,0,2,2,2008-11-02,0
12,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Sporting Lokeren,LOK,RAEC Mons,MON,0,0,0,2008-11-01,0
13,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,FCV Dender EH,DEN,KVC Westerlo,WES,2,2,4,2008-11-01,0
14,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,KV Mechelen,MEC,KSV Roeselare,ROS,1,2,3,2008-11-01,0
15,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Royal Excel Mouscron,MOU,KSV Cercle Brugge,CEB,0,1,1,2008-11-01,0
16,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Tubize,TUB,KRC Genk,GEN,1,3,4,2008-11-01,0
17,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02 00:00:00,Beerschot AC,BAC,RSC Anderlecht,AND,1,3,4,2008-11-02,0
18,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,RSC Anderlecht,AND,Sporting Lokeren,LOK,2,3,5,2008-11-08,0
19,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,RAEC Mons,MON,Royal Excel Mouscron,MOU,0,0,0,2008-11-08,0
20,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09 00:00:00,Sporting Charleroi,CHA,Club Brugge KV,CLB,2,2,4,2008-11-09,0
21,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-07 00:00:00,KSV Cercle Brugge,CEB,SV Zulte-Waregem,ZUL,2,0,2,2008-11-07,0
22,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KAA Gent,GEN,FCV Dender EH,DEN,1,1,2,2008-11-08,0
23,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KSV Roeselare,ROS,Tubize,TUB,1,2,3,2008-11-08,0
24,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KV Kortrijk,KOR,KV Mechelen,MEC,0,0,0,2008-11-08,0
25,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KVC Westerlo,WES,KRC Genk,GEN,1,0,1,2008-11-08,0
26,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09 00:00:00,Beerschot AC,BAC,Standard de Liège,STL,1,3,4,2008-11-09,0
27,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-16 00:00:00,Club Brugge KV,CLB,RSC Anderlecht,AND,1,1,2,2008-11-16,0
28,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15 00:00:00,KRC Genk,GEN,KSV Roeselare,ROS,1,1,2,2008-11-15,0
29,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15 00:00:00,SV Zulte-Waregem,ZUL,Beerschot AC,BAC,2,2,4,2008-11-15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08 00:00:00,Grasshopper Club Zürich,GRA,Lugano,LUG,6,1,7,2015-08-08,10
25950,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08 00:00:00,FC Luzern,LUZ,FC Basel,BAS,1,3,4,2015-08-08,10
25951,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,FC St. Gallen,GAL,FC Zürich,ZUR,0,2,2,2015-08-09,10
25952,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,FC Vaduz,VAD,FC Sion,SIO,1,1,2,2015-08-09,10
25953,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,BSC Young Boys,YB,FC Thun,THU,3,1,4,2015-08-09,10
25954,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,FC Basel,BAS,FC Thun,THU,3,1,4,2015-08-12,10
25955,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,BSC Young Boys,YB,Lugano,LUG,0,1,1,2015-08-12,10
25956,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,FC Luzern,LUZ,FC St. Gallen,GAL,0,1,1,2015-08-12,10
25957,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13 00:00:00,FC Sion,SIO,FC Zürich,ZUR,3,1,4,2015-08-13,10
25958,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13 00:00:00,FC Vaduz,VAD,Grasshopper Club Zürich,GRA,3,3,6,2015-08-13,10
25959,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22 00:00:00,Lugano,LUG,FC Basel,BAS,1,3,4,2015-08-22,10
25960,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC Sion,SIO,BSC Young Boys,YB,1,3,4,2015-08-23,10
25961,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC St. Gallen,GAL,Grasshopper Club Zürich,GRA,0,2,2,2015-08-23,10
25962,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC Thun,THU,FC Vaduz,VAD,1,0,1,2015-08-23,10
25963,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22 00:00:00,FC Zürich,ZUR,FC Luzern,LUZ,2,5,7,2015-08-22,10
25964,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29 00:00:00,Lugano,LUG,FC Luzern,LUZ,0,1,1,2015-08-29,10
25965,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29 00:00:00,FC Vaduz,VAD,FC St. Gallen,GAL,1,0,1,2015-08-29,10
25966,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,FC Thun,THU,FC Sion,SIO,0,2,2,2015-08-30,10
25967,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,FC Basel,BAS,FC Zürich,ZUR,3,1,4,2015-08-30,10
25968,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,Grasshopper Club Zürich,GRA,BSC Young Boys,YB,3,2,5,2015-08-30,10
25969,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12 00:00:00,FC Basel,BAS,FC St. Gallen,GAL,2,1,3,2015-09-12,10
25970,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12 00:00:00,BSC Young Boys,YB,FC Vaduz,VAD,4,0,4,2015-09-12,10
25971,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Luzern,LUZ,Grasshopper Club Zürich,GRA,3,3,6,2015-09-13,10
25972,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Zürich,ZUR,FC Thun,THU,3,3,6,2015-09-13,10
25973,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Sion,SIO,Lugano,LUG,3,0,3,2015-09-13,10
25974,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22 00:00:00,FC St. Gallen,GAL,FC Thun,THU,1,0,1,2015-09-22,10
25975,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,FC Vaduz,VAD,FC Luzern,LUZ,1,2,3,2015-09-23,10
25976,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,Grasshopper Club Zürich,GRA,FC Sion,SIO,2,0,2,2015-09-23,10
25977,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22 00:00:00,Lugano,LUG,FC Zürich,ZUR,0,0,0,2015-09-22,10
25978,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,BSC Young Boys,YB,FC Basel,BAS,4,3,7,2015-09-23,10

More about preprocessing in:
* https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing